The deployment size should be allowed to reach the value 0
artemiscloud/activemq-artemis-self-provisioning-plugin pull request #282
Opened 2024-09-02 13:19 UTC by Msarawan

Updated the deployment size should be allowed to reach the value 0.

![Screenshot from 2024-09-02 18-30-48](https://github.com/user-attachments/assets/3d038f07-ca55-4677-aaff-8d6516435874)

fixes: [#276](https://github.com/artemiscloud/activemq-artemis-self-provisioning-plugin/issues/276)

2024-09-02 13:23 UTC, lavocatt requested changes
This is good, I believe that there were tests testing that the value could not go below 1, they should also be updated :slightly_smiling_face: 

edit: this is what is failing:

![image](https://github.com/user-attachments/assets/1ba3bc44-c8fe-4aa9-a830-9ac6fd0fce82)

2024-09-02 13:25 UTC, Msarawan commented
> This is good, I believe that there were tests testing that the value could not go below 1, they should also be updated 🙂
> 
> edit: this is what is failing:
> 
> ![image](https://private-user-images.githubusercontent.com/86971992/363703294-1ba3bc44-c8fe-4aa9-a830-9ac6fd0fce82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyODM3NzAsIm5iZiI6MTcyNTI4MzQ3MCwicGF0aCI6Ii84Njk3MTk5Mi8zNjM3MDMyOTQtMWJhM2JjNDQtYzhmZS00YWE5LWE4MzAtOWFjNmZkMGZjZTgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDEzMjQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4YWE2Nzg5OGZmNTcwMTViMTJjZjdlZjlmZGMxMWQ5ZjdiYjlmN2MxZWQwNmY1YjI0YjBlYTdhODUxMmEzM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kiq1w6U6OWsFvv2nKSh67g19Ay8rCp0Tb0GMi0ZhAfE)

yes i am updating the tests.

2024-09-02 13:32 UTC, lavocatt commented on src/reducers/7.12/reducer.test.ts
> +    expect(newState.cr.spec.deploymentPlan.size).toBe(0);
Can you add a state manipulation in this test to try to decrement under 0 and make sure that the value doesn't go below 0 please?

```
    const newState = artemisCrReducer(initialState, {
      operation: ArtemisReducerOperations.decrementReplicas,
    });
    // decrementing from 0 should leave a value of zero
    expect(newState.cr.spec.deploymentPlan.size).toBe(0);
```

2024-09-03 07:35 UTC, lavocatt approved these changes
All good to me! Good work

2024-09-03 07:35 UTC, merged

2024-09-03 07:38 UTC, Msarawan commented
> All good to me! Good work

Thank you!