[#326] Add a YAML tab on the Broker details view
artemiscloud/activemq-artemis-self-provisioning-plugin pull request #334
Opened 2024-12-04 08:56 UTC by Msarawan

Added a YAML tab on the Broker Details view to make it easier for users to access the Broker's details.

fixes: [#326](https://github.com/artemiscloud/activemq-artemis-self-provisioning-plugin/issues/326)

2024-12-05 16:35 UTC, lavocatt commented on src/brokers/broker-details/components/yaml/Yaml.container.tsx
> +    <Page>
This can't be a `<Page>`, because it's inside a `<Page>` already, it can only be a `<PageSection>`

2024-12-05 16:35 UTC, lavocatt requested changes
This is all very good work, congrats. The only thing that we need to focus on now is to fix the problem with the vertical space the yaml editor is taking.

If you look at all the other views, the yaml editor is always taking the maximum vertical space possible without going overboard. In contrary, in the implementation you have now, the buttons appear under the page.

2024-12-11 09:48 UTC, lavocatt reviewed
Good work! It's working now, that's good. There are a few things to improve in the PR itself:

- We need to split the work a bit, there's a first commit that is about adding a YAML tab with all it needs (including removing the Page and PageSection in the broker details page, and this entry point only) and there's another commit that is removing the Page and PageSection everywhere else, this has to be with another github issue number or NO-ISSUE as it's unrelated to adding the YAML tab in the broker details page, even though we've learned that Page and PageSection are bad doing this work.
- We need to have more tests to make sure there's no regressions.

2024-12-11 09:51 UTC, Msarawan commented on src/brokers/broker-details/BrokerDetails.container.tsx
> +      {loadingBrokerCr && <Spinner size="md" />}
sure, i will add...

2024-12-12 07:53 UTC, Msarawan commented
This PR is recreated on the new `arkmq-org` repo: [PR#4](https://github.com/arkmq-org/activemq-artemis-self-provisioning-plugin/pull/4)

2025-09-17 07:33 UTC, closed without merging