upstream gh action updates
artemiscloud/activemq-artemis-self-provisioning-plugin pull request #35
Opened 2023-05-08 07:02 UTC by AjayJagan

Changing the gh actions as it is done in other artemiscloud repositories.

2023-05-10 12:02 UTC, ajaypratap003 commented on .github/workflows/ci.yml
> +      - uses: actions/setup-node@v3
```suggestion
     - name: Set up Node.js
        uses: actions/setup-node@v3
```

2023-05-10 12:20 UTC, ajaypratap003 commented on .github/workflows/ci.yml
> +      - run: yarn install --frozen-lockfile
```suggestion
     -  name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        shell: bash
        run: yarn install --frozen-lockfile
```

@AjayJagan Let's keep existing separate cache file i.e. `actions/cache-restore/action.yml` and modify if any changes required.  There are some check missing here for cache like  if: steps.node-cache.outputs.cache-hit != 'true'.

2023-05-10 12:29 UTC, ajaypratap003 commented on .github/workflows/ci.yml
> +        if: ${{ github.event_name == 'push' }}
```suggestion

```
We don't need this check as we need to make sure docker image build is working fine on PR. Below push check is fine for push the image.

2023-05-10 12:44 UTC, ajaypratap003 requested changes
Added few inline suggestions/comments. 
I noticed that build  docker image job is not running due to `push` check which is not required. 
Rest looks good to me.

2023-05-10 12:46 UTC, ajaypratap003 commented
@brusdev @RoddieKieley Please have a look into this PR whenever you guys have time.

2023-05-16 09:04 UTC, ajaypratap003 approved these changes
LGTM

2023-05-16 16:32 UTC, brusdev approved these changes
@AjayJagan nice work!!!

Could you squash your commits before merging this PR?

2023-05-16 17:07 UTC, AjayJagan commented
> @AjayJagan nice work!!!
> 
> Could you squash your commits before merging this PR?

Thanks a lot! and yes we will sqash before merge(owing to a lot of commits 😅)

2023-05-17 19:44 UTC, merged